### ISSUE TITLE
How to enable profiling via flag

### ISSUE THREAD

**Issue by rhd** [jawher/mow.cli#12]
Hi, how would I integrate profiling into my your app?

https://github.com/pkg/profile

I have to call something right when the app starts and right when it exits (or use defer as in the example). But I only want it enabled when I pass a flag via the command line.

Would I have to use a global flag and copy/paste the same code in each command?

Thanks!

**Comment by jawher** [comment]
Interesting use case, thanks for bringing it up !

You are right in that mow.cli does not provide a way to achieve what you want. Not without, as you pointed it out, copying and pasting the necessary calls in every command.

I'll be thinking of a more elegant way of achieving this.
Right now, I'm guessing it would look like:

```go
app := cli.App("MyApp", "A super duper app")
enableProfiling := app.BoolOpt("p profile", false, "enable profiling")

app.Before = func() {
  if *enableProfiling {
    profile.Start()
  }
}

app.After = func() {
  if *enableProfiling {
    profile.Stop()
  }
}

app.Command("command1", "...", func(cmd *cli.Cmd) {
    ...
})

app.Command("command2", "...", func(cmd *cli.Cmd) {
    ...
})
```

Where the `Before` and `After` functions will be called before and after the invoked command's action.

**Comment by rhd** [comment]
That would be a perfect solution. FYI, I'm writing a cli app that requires username/password authentication and I'm currently coping/pasting the same code in each command. This solution fixes that issue too!

One request, would it be possible to check the return value in app.Before() or at least give a way for the command not to continue if, say, authentication fails or some other error occurs.

Do you plan on making this more generic, so you could have a cmd.Before/After as well?

Appreciate your work. Thanks!

**Comment by jawher** [comment]
> One request, would it be possible to check the return value in app.Before() or at least give a way for the command not to continue if, say, authentication fails or some other error occurs.

Wouldn't a call to `os.Exit` suffice ?

> Do you plan on making this more generic, so you could have a cmd.Before/After as well?

Sure: app is really a command, so the before/after solution would work the same everywhere.

> Appreciate your work. Thanks!

Thank you for the kind words :)

**Comment by rhd** [comment]
> Wouldn't a call to os.Exit suffice ?

Hmm, I can't think of a reason it would not suffice - good solution that doesn't require any extra plumbing.

> Sure: app is really a command, so the before/after solution would work the same everywhere.

Perfect, thanks!

**Comment by jawher** [comment]
@rhd: can you give #15 a look please ? You feedback on the proposed solution, and test results would be most welcome !

**Comment by rhd** [comment]
@jawher Without actually checking out the code and testing it, the PR looks really good to me. Looking forward to this getting merged! Great addition.

**Comment by jawher** [comment]
Thanks again @rhd for requesting this feature: it is now supported and `mow.cli` is the better for it !

**Comment by rhd** [comment]
Amazing... Thank you. I'll try to test it out tonight.

Btw, you should get this added to awesome go.
https://github.com/avelino/awesome-go
