### ISSUE TITLE
Request: Long option only.

### ISSUE THREAD

**Issue by november-eleven** [jawher/mow.cli#13]
Hello,

This library is neat, however, it would be perfect if its was possible to declare an option in long format
only.

For example using `StringOpt`:

```go
host := app.String(cli.StringOpt{
    Name:  "host",
    Value: "127.0.0.1",
    Desc:  "Hostname",
    LongOptOnly: true,
})
```

Thank you in advance.

**Comment by jawher** [comment]
Hi,

I'm not sure I understand the issue here: if you don't give the option a short name, like you did in the example above, the option can only be set via its long name.

Or am I missing something ?

**Comment by november-eleven** [comment]
Hello,

No you right, my bad. I was using an old version and the option with only long name was causing panic error - or I was doing something wrong - its working just fine now.

Thank you.
