### ISSUE TITLE
How to write option's argument in Spec?

### ISSUE THREAD

**Issue by kk44** [jawher/mow.cli#14]
hi, jawher

here is my code:
```
package main

import (
	"fmt"
	"github.com/jawher/mow.cli"
	"os"
)

func main() {
	app := cli.App("greet", "Greet")
	app.Spec = "-c [NAME]"
	// how to write the "c" option's argument?

	name := app.StringArg("NAME", "stranger", "Your name")
	count := app.IntOpt("c count", 1, "the count")

	app.Action = func() {
		for i := 0; i < *count; i++ {
			fmt.Printf("Hello %s\n", *name)
		}
	}
	app.Run(os.Args)
}
```

then run:

```
$ go run greet.go -h

Usage: greet -c [NAME]

Greet

Arguments:
  NAME="stranger"   Your name

Options:
  -c, --count=1   the count
```

meaning it is not possible to tell whether [NAME] is option's argument or positional argument

I want to get the help "Usage: greet -c COUNT [NAME]", the COUNT is "c" option's argument, and the "[NAME]" is positional argument.

Thank you!

**Comment by jawher** [comment]
Hi,

Unfortunately, and in its current form, `mow.cli` doesn't support what you're trying to achieve.

Just thinking out loud here, but I think this could be achieved by extending the options structs with a new field, say `InlineDesc` for example:

```go
count = app.Int(IntOpt{
    Name:  "c count",
    Value: 1,
    Desc:  "the count",
    InlineDesc: "<num>",
})
```

This new field, when set, will be printed alongside the option in the help messages:

```
Usage: greet -c=<num> [NAME]

Greet

Arguments:
  NAME="stranger"   Your name

Options:
  -c, --count=1   the count
```

Things to think about:
* the `=` sign or something similar must be present, else the help messages become ambiguous, like in the example you give where `COUNT` looks like an argument.
* How to show the inline description for option groups, e.g. `-crx` for example ?
* Can't think of any other thing right now, but I'm sure other issues will pop up.

I would appreciate your feedback on this: does the solution I propose solve your problem ? if not, do you have another suggestion ?

**Comment by kk44** [comment]
Hi, jawher
Thank you for your help!

I think we can ignore the option's argument before parse the Spec. For example, ignore the "=\<count\>" in the Spec "-c=\<count\> [NAME]". 

git diff:

```
$ git diff
diff --git a/commands.go b/commands.go
index 752fac4..7a64f01 100644
--- a/commands.go
+++ b/commands.go
@@ -5,6 +5,7 @@ import (
        "flag"
        "fmt"
        "os"
+       "regexp"
        "strings"
        "text/tabwriter"
 )
@@ -19,6 +20,7 @@ type Cmd struct {
        Action func()
        // The command options and arguments
        Spec string
+       spec string
        // The command error handling strategy
        ErrorHandling flag.ErrorHandling

@@ -198,6 +200,9 @@ func (c *Cmd) doInit() error {
                        c.Spec += arg.name + " "
                }
        }
+       c.spec = c.Spec
+       re := regexp.MustCompile(`\[?=\]?[^\s\)\]\|\.]+`)
+       c.Spec = re.ReplaceAllString(c.Spec, "")
        fsm, err := uParse(c)
        if err != nil {
                return err
@@ -233,7 +238,7 @@ func (c *Cmd) PrintHelp() {
        path := strings.Join(full, " ")
        fmt.Fprintf(out, "\nUsage: %s", path)

-       spec := strings.TrimSpace(c.Spec)
+       spec := strings.TrimSpace(c.spec)
        if len(spec) > 0 {
                fmt.Fprintf(out, " %s", spec)
        }
```

Test:

```
bash-3.2$ cat greet.go
package main

import (
	"fmt"
	"github.com/jawher/mow.cli"
	"os"
)

func main() {
	app := cli.App("greet", "Greet")
	app.Spec = "[-c=<count>|--count=COUNT] [NAME]"

	name := app.StringArg("NAME", "stranger", "Your name")
	count := app.IntOpt("c count", 1, "the count")

	app.Action = func() {
		for i := 0; i < *count; i++ {
			fmt.Printf("Hello %s!\n", *name)
		}
	}
	app.Run(os.Args)
}
bash-3.2$ go build greet.go
bash-3.2$ ./greet -h

Usage: greet [-c=<count>|--count=COUNT] [NAME]

Greet

Arguments:
  NAME="stranger"   Your name

Options:
  -c, --count=1   the count
bash-3.2$ ./greet
Hello stranger!
bash-3.2$ ./greet -c 2
Hello stranger!
Hello stranger!
```

It must have a "=" before option's argument in Spec.

Also, the Spec can be:
```
	app.Spec = "--count=COUNT [NAME]"
	app.Spec = "--count=<count> [NAME]"
	app.Spec = "--count[=]COUNT [NAME]"
	...
```

But, it has not be tested with subcommand.

**Comment by jawher** [comment]
@kk44 yeah, you're totally right: the inline values definitely go into the spec strings.

I'll get working on it.

**Comment by jawher** [comment]
@kk44: A working version in #16.
Your feedback would be appreciated !

**Comment by kk44** [comment]
Wow! It works! Thank you!
