### ISSUE TITLE
Allow arbitrary args and flags

### ISSUE THREAD

**Issue by zpatrick** [jawher/mow.cli#21]
Hi Jawher,

Is there is a way to allow arbitrary arguments and flags in a command? I have a script which wraps another tool and want to give users the ability to pass any args/flags to the underlying tool as if they were using it directly. I'm able to pass arbitrary string args using: 
```
app := cli.App(...)
...
app.Command("tool", "Send a command directly to the tool using the INSTANCE configuration", func(cmd *cli.Cmd) {
	instance := cmd.String(InstanceArg)
	args := cmd.StringsArg("ARGS", nil, "tool arguments")
	cmd.Spec = "INSTANCE [ARGS...]"

	cmd.Action = func() {
		// pass *args along to tool
	}
})
```
However, I haven't figured out a clean way to allow arbitrary flags as well. Ideally, I would be able to run the command like:
```
> main.go tool INSTANCE [args...] [flags...]
```

 I don't want to clutter up my code with all of the potential args/flags for underlying tool, and would prefer not to manually parse `os.Args` before calling `app.Run`. Any suggestions?

Regards,
ZPatrick

**Comment by jawher** [comment]
Hi,

The `--` is what you're looking for (see [this section of the README)[https://github.com/jawher/mow.cli#operators]).

In your case:

```go
app := cli.App(...)
...
app.Command("tool", "Send a command directly to the tool using the INSTANCE configuration", func(cmd *cli.Cmd) {
    instance := cmd.String(InstanceArg)
    args := cmd.StringsArg("ARGS", nil, "tool arguments")
    cmd.Spec = "INSTANCE [-- ARGS...]"

    cmd.Action = func() {
        // pass *args along to tool
    }
})
```

You can then call your command like this:

```
app tool cp -R source dest
```

And `instance` will be populated with `"cp"` and `args` with `["-R", "source", "dest"]`

**Comment by zpatrick** [comment]
Just what I was looking for, thanks!
