### ISSUE TITLE
Poor performance with multiple nested options

### ISSUE THREAD

**Issue by schmich** [jawher/mow.cli#28]
In the application below, running `ward add --help` or any other variation of `add` is very slow (>30s). I'm guessing it's because of the complicated spec with multiple nested options. I haven't done any profiling yet, so I can't tell you where it's spending time.

For context, this is for a command-line password manager. Specifically, the `add` command lets you add a new credential (e.g. `ward add --login "foo@foo.net"`), but it also has a built-in password generator with its own sub-options, so `ward add --login "foo@foo.net" --gen --length 15 --no-symbol` is valid as well.

I'm running on Windows 10 64-bit with Go 1.5.1.

```go
// ward.go
package main

import (
  "github.com/jawher/mow.cli"
  "fmt"
  "os"
)

func run(args []string) {
  ward := cli.App("ward", "Secure password manager - https://github.com/schmich/ward")

  ward.Command("add", "Add a new credential.", func(cmd *cli.Cmd) {
    cmd.Spec = "[--login] [--realm] [--note] [--no-copy] [--gen [--length] [--min-length] [--max-length] [--no-upper] [--no-lower] [--no-digit] [--no-symbol] [--no-similar] [--min-upper] [--max-upper] [--min-lower] [--max-lower] [--min-digit] [--max-digit] [--min-symbol] [--max-symbol] [--exclude]]"

    _ = cmd.StringOpt("login", "", "Login for credential, e.g. username or email.")
    _ = cmd.StringOpt("realm", "", "Realm for credential, e.g. website or WiFi AP name.")
    _ = cmd.StringOpt("note", "", "Note for credential.")
    _ = cmd.BoolOpt("no-copy", false, "Do not copy generated password to the clipboard.")
    _ = cmd.BoolOpt("gen", false, "Generate a password.")
    _ = cmd.IntOpt("length", 0, "Password length.")
    _ = cmd.IntOpt("min-length", 30, "Minimum length password.")
    _ = cmd.IntOpt("max-length", 40, "Maximum length password.")
    _ = cmd.BoolOpt("no-upper", false, "Exclude uppercase characters in password.")
    _ = cmd.BoolOpt("no-lower", false, "Exclude lowercase characters in password.")
    _ = cmd.BoolOpt("no-digit", false, "Exclude digit characters in password.")
    _ = cmd.BoolOpt("no-symbol", false, "Exclude symbol characters in password.")
    _ = cmd.BoolOpt("no-similar", false, "Exclude similar characters in password.")
    _ = cmd.IntOpt("min-upper", 0, "Minimum number of uppercase characters in password.")
    _ = cmd.IntOpt("max-upper", -1, "Maximum number of uppercase characters in password.")
    _ = cmd.IntOpt("min-lower", 0, "Minimum number of lowercase characters in password.")
    _ = cmd.IntOpt("max-lower", -1, "Maximum number of lowercase characters in password.")
    _ = cmd.IntOpt("min-digit", 0, "Minimum number of digit characters in password.")
    _ = cmd.IntOpt("max-digit", -1, "Maximum number of digit characters in password.")
    _ = cmd.IntOpt("min-symbol", 0, "Minimum number of symbol characters in password.")
    _ = cmd.IntOpt("max-symbol", -1, "Maximum number of symbol characters in password.")
    _ = cmd.StringOpt("exclude", "", "Exclude specific characters from password.")
  })

  fmt.Println("Run.")
  ward.Run(args)
}

func main() {
  fmt.Println("Begin.")
  run(os.Args)
  fmt.Println("Fin.")
}
```

**Comment by schmich** [comment]
Following the steps [here](https://medium.com/@tjholowaychuk/profiling-golang-851db2d9ae24), I'm seeing the profile below (or [see the call tree here](https://github.com/jawher/mow.cli/files/110696/profile.pdf)). Everything seems to point to [`state.has`](https://github.com/jawher/mow.cli/blob/995a6dc78cd1b43d3145ca69ef15cfec07e06713/fsm.go#L53) as the bottleneck.

```
2790.01s of 2836.33s total (98.37%)
Dropped 191 nodes (cum <= 14.18s)
      flat  flat%   sum%        cum   cum%
  2577.42s 90.87% 90.87%   2577.45s 90.87%  github.com/jawher/mow%2ecli.(*state).has
    90.75s  3.20% 94.07%    217.36s  7.66%  runtime.scanobject
    67.32s  2.37% 96.44%     67.32s  2.37%  runtime.heapBitsForObject
    48.04s  1.69% 98.14%     59.93s  2.11%  runtime.greyobject
     3.24s  0.11% 98.25%   2582.97s 91.07%  github.com/jawher/mow%2ecli.(*state).simplifySelf
     1.90s 0.067% 98.32%    150.65s  5.31%  runtime.gcDrainUntilPreempt
     0.94s 0.033% 98.35%        78s  2.75%  runtime.gcDrain
     0.36s 0.013% 98.37%   2584.85s 91.13%  github.com/jawher/mow%2ecli.simplify
     0.04s 0.0014% 98.37%    228.69s  8.06%  runtime.gcBgMarkWorker
         0     0% 98.37%   2557.03s 90.15%  github.com/jawher/mow%2ecli.(*Cli).Run
         0     0% 98.37%   2561.70s 90.32%  github.com/jawher/mow%2ecli.(*Cli).parse
         0     0% 98.37%   2566.07s 90.47%  github.com/jawher/mow%2ecli.(*Cmd).doInit
         0     0% 98.37%   2563.82s 90.39%  github.com/jawher/mow%2ecli.(*Cmd).parse
         0     0% 98.37%   2572.24s 90.69%  github.com/jawher/mow%2ecli.(*state).simplify
         0     0% 98.37%   2570.86s 90.64%  github.com/jawher/mow%2ecli.(*uParser).parse
         0     0% 98.37%   2568.29s 90.55%  github.com/jawher/mow%2ecli.uParse
         0     0% 98.37%   2538.80s 89.51%  main.main
         0     0% 98.37%   2550.34s 89.92%  main.run
         0     0% 98.37%   2743.06s 96.71%  runtime.goexit
         0     0% 98.37%   2525.75s 89.05%  runtime.main
```

**Comment by jawher** [comment]
Ouch !

Thanks @schmich for finding and reporting this issue !
I'm out of town this weekend but I'll look into this as soon as I'm back.

**Comment by jawher** [comment]
@schmich progress report: I've looked into the issue, and the root cause is not how `sate.has` is implemented in particular.
What's going on here is that `mow.cli` uses a state machine to parse and validate the user provided options.
State machines are inherently sequential and "ordered".
What that means is that by default, it will accept options only in their order in the spec string, which is not how options should work.

To work around this, I thought I devised a clever solution, which turned out to be stupid, as proven by the issue you're facing.
The faulty solution works as follow: whenever 2 consecutive options are detected in the spec, their separate state machines were not simply linked one after the other (since that would enforce order), instead, a new state machine accepting both possible ordering of these options is constructed.
See [over here for a more detailed description of how this works](https://jawher.me/2015/01/18/parsing-command-line-arguments-finite-state-machine-backtracking/#sequence).

The problem with this approach is that the number of combinations grows as a factorial of the number of options. With around 20 in your case, that generates a huge number of states, hence the slowdown (and also memory consumption).

I'll have scrap this part and think of a completely different way of doing this.

Thanks again for reporting the issue, and I'll keep you informed on the progress.

**Comment by schmich** [comment]
@jawher thanks for looking into this so quickly. The problem definitely makes sense, but I can see how a fix would be tricky given the current approach. I noticed the factorial nature of the problem, too, since the program runs quickly if I remove just a handful of the options.

From what I can tell, in some ways, you're paralleling a regex library. You're constructing a parser on-the-fly from a string, and then using that parser to process some input. I've played a lot with static parser generators, but not much with regex/FSM parsing internals. I wonder how regex engines deal with this kind of input, e.g. could I write a regex that efficiently matches my command spec? I realize regex doesn't have the concept of unordered-ness, but you can kind of approximate it with repetition and alternation, e.g. `[--foo] [--bar] [--baz]` is approximated by `(--foo|--bar|--baz)+`, except that the regex allows for unbounded repetition of any of the options.

Thanks for your effort on this project, by the way. I evaluated and passed up a number of other libraries that were lacking compared to what you had done here. Command-line parsing is oddly complex.

**Comment by jawher** [comment]
@schmich 
You're absolutely right: I'm paralleling how (many) regex engines work: construct a state machine from the user's input and use it to validate and extract info from another set of inputs.

You can go quite a way implementing arguments parsing using a regex, but I don't think you'd be able to handle many of the subtleties inherent to CLIs:

- options folding: how to interpret `-abc`: is it `-a -b -c` ? or `-a=bc` ? or `-a -b=c` ?
- end of options `--` operator: 
- etc.

**Comment by jawher** [comment]
@schmich Also, I would be grateful if you could test #29 which should fix the performance (and memory consumption) issue you're having with ward.

**Comment by schmich** [comment]
@jawher :+1: Looks great. Incredibly fast. All tests are passing on my side with this change incorporated. Thanks again for fixing this so quickly. Feel free to close this issue.
