### ISSUE TITLE
custom types via flag.Value

### ISSUE THREAD

**Issue by tv42** [jawher/mow.cli#32]
Hi. I can't see anything in mow.cli taking options/arguments of a non-basic type, just string/int/bool. What about the functionality of `flag.Var` / `flag.Value`?

https://golang.org/pkg/flag/#Var

https://golang.org/pkg/flag/#Value

**Comment by tv42** [comment]
Also this would solve https://github.com/jawher/mow.cli/issues/5

**Comment by jawher** [comment]
@tv42 : Thanks for the suggestion, Var/Value would be a great addition to mow.cli.

While I won't be working on this immediately (I'm soon to set off to a 4 week vacation), I's definitely in the top of my todo list for future work, unless of course you feel like giving it a shot ?

**Comment by jawher** [comment]
A quick update regarding this issue: I finally got something working in:

https://github.com/jawher/mow.cli/tree/issue32-handle-var-value-flags

What remains to be done:

* Documentation (GoDoc and README)
* Examples
