### ISSUE TITLE
Possible to detect whether a value was specified by the user or is just the default value?

### ISSUE THREAD

**Issue by evantorrie** [jawher/mow.cli#35]
Is it possible to distinguish between a default value provided to `<type>Opt()` versus an explicit user supplied value?

I'm guessing the likely suggested approach is just to make the default something a user would never choose, and then check to see if the value is different from that.. but just wondering if this is something that has been considered?

**Comment by jawher** [comment]
@evantorrie Thanks for raising the issue.

> Is it possible to distinguish between a default value provided to <type>Opt() versus an explicit user supplied value?

The answer is no, there is nothing in `mow.cli` that supports this use case.

Do you have a specific example in mind ?
And how would you see such a feature implemented ? Since creating a flag or an argument returns a single result (where the value will be stored) ?

**Comment by evantorrie** [comment]
Yes, I don't see how such a feature could be implemented with the current API.

The general example is one where the default may be a "soft" default, i.e. could be changed by later code if circumstances require it -- whereas if a user supplied an actual value, it would be a "hard" value.  Particular example is one related to specification of allowable memory for a container where the required amount is not known until well after processing the command line options, where if nothing was specified, the system would later use the memory specified by container meta-data, whereas if a user explicitly specified a value, it would override the container meta-data.

Probably just adding another flag (something like "-f" for force) is sufficient in my case, but just thought I'd bring it up.

**Comment by jawher** [comment]
Fixed with #38
