### ISSUE TITLE
Aliasing commands

### ISSUE THREAD

**Issue by gotwarlost** [jawher/mow.cli#37]
It doesn't look like it is possible to have aliases for [sub-] commands? 

For example:

```
some-app cp|copy SRC DEST
```

Should this be supported?

**Comment by jawher** [comment]
@gotwarlost Looks useful and relevant to me 👍 

Want to give it a shot ? It shouldn't be too hard to implement. Something like:

```go
.Command("copy cp", "Copy files around", func(cmd *cli.Cmd) {
    // initialize the run command here
})
```

Then split the command name around spaces.

**Comment by gotwarlost** [comment]
OK, let me take a crack when I get some time.

**Comment by gotwarlost** [comment]
I should add: this is a wonderful library that has become the de-facto standard where I work.

**Comment by jawher** [comment]
@gotwarlost 

> OK, let me take a crack when I get some time.

Don't hesitate to ask if you have any question 👍 

> I should add: this is a wonderful library that has become the de-facto standard where I work.

Thank you so much for the kind words ! Glad to receive such feedback and to know that something I built proves useful to others 😀

**Comment by codykrieger** [comment]
@gotwarlost: FYI: I took a stab at this in #40. :)
