### ISSUE TITLE
feature: support long descriptions for subcommands

### ISSUE THREAD

**Issue by drewfish** [jawher/mow.cli#45]
I have a subcommand where several of the options take a string, which are interpreted the same way for all of these options. Instead of giving details of possible string values for each options, I'd like to add this to the description of the subcommand.

Currently I can use a multi-line string for the description of the subcommand, and this works well if I do `cmd subcmd --help`. However, if I just do `cmd` or `cmd --help` it shows the _full_ description for that subcommand (instead of just a one-line summary) making the output quite hard to read.

It would be nice if there was a way to specify the "long" and "short" description for the subcommand. The short (one-line) description would only be shown when that subcommand is listed with other subcommands. The long description would be shown when help is given only for that subcommand.

**Comment by drewfish** [comment]
One idea is to keep the API as it exists today, and the "short" description (shown when a bunch of subcommands are listed together) is just the first line of command description.

**Comment by jawher** [comment]
Would the `LongDesc`  field in `Cmd` be suitable for your need ? https://godoc.org/github.com/jawher/mow.cli#Cmd

Given this conf:

```go
app := cli.App("app", "desc")
app.BoolOpt("f", false, "option desc")
app.Run(os.Args)
```

Calling `--help`  would normally produce the following output:

```
Usage: app [OPTIONS]

desc

Options:
  -f=false     option desc
```

But if you set the `app.LongDesc`:

```go
app := cli.App("app", "desc")
app.BoolOpt("f", false, "option desc")
app.LongDesc = `
Lorem ipsum dolor sit amet, liber gubergren pro ut, perpetua definiebas complectitur vel ex.
Augue assueverit ad ius, no minimum ullamcorper vim. Sea mazim invidunt te.
Appareat omittantur ex est.
Expetenda efficiantur id duo.
No mei dicam affert dissentias, lorem accommodare pri cu, eu novum facete vulputate est.
`
app.Run(os.Args)
```

It would instead produce:

```
Usage: app [OPTIONS]


Lorem ipsum dolor sit amet, liber gubergren pro ut, perpetua definiebas complectitur vel ex.
Augue assueverit ad ius, no minimum ullamcorper vim. Sea mazim invidunt te.
Appareat omittantur ex est.
Expetenda efficiantur id duo.
No mei dicam affert dissentias, lorem accommodare pri cu, eu novum facete vulputate est.


Options:
  -f=false     option desc
```

**Comment by drewfish** [comment]
Something like LongDesc() for cli.Cmd would be perfect, but it doesn't appear to exist.

**Comment by drewfish** [comment]
Oh, it's field, and it works perfectly. (Sorry, I'm new to golang.) Thanks!

**Comment by jawher** [comment]
@drewfish No worries, glad it worked out for you 😄
