### ISSUE TITLE
Consider tagging versions

### ISSUE THREAD

**Issue by silasdavis** [jawher/mow.cli#48]
I know there is a tradition in golang of not tagging versions and just running off master, but I am managing my dependencies with a manifest file and it would be convenient to be able to specify a version tag. I can do the same with a commit hash but isn't quite as nice. Would you consider cutting some tagged releases?

Thanks for the library.

**Comment by jawher** [comment]
@silasdavis Thanks for raising the issue.

With mow.cli, the promise is: master will always keep backward compatibility.
If ever I needed to introduce breaking changes, the plan was to create another repo, `mow.cli.v2` for example.

I know this is just a promise and not necessarily *unbreakable*, but it worked so far.
However, I'm not against using a semver scheme (and tagging), where major will always be fixed to `1`, minor will increment with new features and revision for bug fixes.

I'll give it a try: I'll need to see how to achieve this using travis ideally.

**Comment by jawher** [comment]
@silasdavis Done. The version 1.0.0 was tagged.
