### ISSUE TITLE
Help semantics are a bit confusing...

### ISSUE THREAD

**Issue by DarwinJS** [jawher/mow.cli#52]
Under arguments the generated help says things like: FILE="" - which puts you under the impression you need that exact text like this FILE="c:\some\path\to\a\file.txt", when in reality you substitute the parameter value for the entire string FILE as it appears in the "Usage:" pattern.

I have been caught on this for parameters I don't use much and I observed colleagues who are newer to a given parameter do the same thing - even when they don't do it on familiar parameters.

It seems pretty natural for technical folks to make this assumption - would be nice to align the documentation semantics with the natural perceptions rather than fight them with more documentation.

**Comment by jawher** [comment]
Fair enough.

I'll see what I can do (another way of formatting the default values).
