### ISSUE TITLE
CLI hangs when EnvVar is set

### ISSUE THREAD

**Issue by jdonboch** [jawher/mow.cli#55]
I am having an issue where the CLI will hang when I pass in an invalid flag.  I have created a simplified version of my project to recreate the issue here:

https://github.com/jdonboch/mow-hangs

If I have the environment variable "FARO_HOME" set and I run the above project with an invalid flag argument, mow.cli will hang:

`mow-hangs --invalid-tag api`

If I unset the environment variable, the CLI will return properly with an incorrect usage (expected).

I attached a debugger and it seems to be looping forever in this area of the code:
https://github.com/jawher/mow.cli/blob/master/matchers.go#L250

I haven't had time to debug much as I am not too familiar with the code.  Any work-arounds would also be appreciated.

**Comment by jawher** [comment]
For a quick workaround, you can manually specify a spec string, like the following:

```go
app.Spec="[-c]"
```

(Supposing you have a `-c` option, like in the example repo you linked)

**Comment by jawher** [comment]
Back from vacations.
The issue is now fixed (#56) and a new release (v1.0.2) with the fix is out.

Thanks for finding and raising this *hairy* issue !
