### ISSUE TITLE
Negative values for VarArg() Bug?

### ISSUE THREAD

**Issue by Javyre** [jawher/mow.cli#65]
I noticed that i cannot get a positional `VarArg` with a negative value to work properly...
Here is an example:
```golang
...
type Float32Arg float32

func (fla *Float32Arg) String() string {
    return strconv.FormatFloat(float64(*fla), 'f', -1, 32)
}

func (fla *Float32Arg) Set(s string) error {
    val, err := strconv.ParseFloat(s, 32)
    if err != nil {
        return err
    }
    *fla = Float32Arg(float32(val))
    return err
}
...
```

When i then use it in a `VarArg`
```golang
...
            val := Float32Arg(0)
            cmd.VarArg("VAL", &val, "value")
...
```

i cannot input a negative value because it interprets it as a flag argument:
```
$ ./cmd 10.0    <= works
$ ./cmd -10.0   <= does not work (prints help message because '-10.0' is not a declared flag
```

I am temporarily using `VarOpt` because that woks since its already a flag: (`--val=-10.0` and `-v-10.0` works fine)

Im not very familiar with the internals of this project, but to me it seems that it is a matter of flag parsing/checks preceding positional argument parsing/checks

Is this behaviour a bug?

PS.: Thank u for the beautiful api 👌

**Comment by jawher** [comment]
Thank you for the detailed report and for the kind words 😄 

> Im not very familiar with the internals of this project, but to me it seems that it is a matter of flag parsing/checks preceding positional argument parsing/checks

Indeed, though not exactly a matter of before/after:
By default, positional argument matchers would reject anything starting with a `-`, to avoid accidentally consuming options.

This is a sort of an unwritten law, and the same behaviour can be observed in the almost all command line tools.
For example, all of the following invocations would fail complaining about an uknown/illegal option:

``` shell
# I want to create a file named "-x"
touch -x

# I want to delete a file named "-x"
rm -x

# I want to edit a file named "-z"
vim -z

# I want to copy a file named "-x"
cp -x xcopy

...
```

The usual workaround around this behaviour is using the `--` symbol:

```shell
# This does create a file named -x
touch -- -x

# This does delete the -x file
rm -- -x
```

The same can be used with mow.cli, in your case:

```shell
app cmd -- -1.0
```

Which is, admittedly, not very user friendly.

mow.cli also proposes to place the burden on the developer side> You could use the `--` in the spec of your app/command:

```go
func main() {
	app := cli.App("ussue65", "bug ?")

	val := Float32Arg(0)
	app.VarArg("VAL", &val, "value")
	app.Spec = "-- VAL"

	app.Action = func() {
		fmt.Printf("app.Run(): %v\n", val)
	}
	app.Run(os.Args)
}
```

This instructs mow.cli to behave as if the user inserted a `--` himself.

Would this approach be acceptable for you ?

**Comment by Javyre** [comment]
More than acceptable thank you!
I must've missed it in the docs
