### ISSUE TITLE
Synchronize README.md and doc.go

### ISSUE THREAD

**Issue by pkazmier** [jawher/mow.cli#71]
As I was submitting PRs for some `README.md` enhancements, I noticed that `doc.go` has drifted in numerous spots. I'm more than happy to update `doc.go`, so it matches `README.md` more closely. This would give me an opportunity to learn about `godoc` as I'm new to Go.

Ideally, it would be great if one could be derived from the other, but I'm not familiar with the documentation tools available in Go-land yet. Is there a best practice with this regards?

**Comment by jawher** [comment]
> Ideally, it would be great if one could be derived from the other, but I'm not familiar with the documentation tools available in Go-land yet. Is there a best practice with this regards?

I have no idea to be honest. I haven't look into this.
I agree It would be better thank having to manually keep the 2 (godoc and readme) in sync by hand.

**Comment by pkazmier** [comment]
I'm working on this now and will have something to show by end of the weekend.

**Comment by pkazmier** [comment]
Submitted #72 to address this issue.
