### ISSUE TITLE
CLI parsing chokes when optional value contains `=` char

### ISSUE THREAD

**Issue by coriolinus** [jawher/mow.cli#74]
I'm writing an application that needs to be able to receive base64-encoded data on the command line. However, mow.cli apparently doesn't like that base64 data uses equal signs for padding. Example (slightly modified to preserve NDA'd info):

```sh
$ ex --ns='9bu+xgWuYTq+5kYjWvGNKWC4kF3oFQDLcugyvomXTZk='
Error: incorrect usage
...
```

I believe that this is an issue with equal padding and not other some misconfiguration because trimming the last quartet causes a logic error farther into the program:

```sh
$ ex --ns='9bu+xgWuYTq+5kYjWvGNKWC4kF3oFQDLcugyvomX'
namespace must have size 32; found 30
```

The workaround is clear enough in my case: document that the CLI expects its values stripped of padding, and then insert any necessary padding in the logical portion of the program. However, it would be good if mow.cli were capable of handling this input in the future.

**Comment by jawher** [comment]
Thank you for raising the issue.

I'll look into it !
