### ISSUE TITLE
Float Options

### ISSUE THREAD

**Issue by tcurdt** [jawher/mow.cli#77]
There should be some kind of float type support built-in.

**Comment by tcurdt** [comment]
I was trying the following:
```
  ratio := cmd.Float32(cli.Float32Opt{
    Name:   "r ratio",
    Value:  0.8,
    Desc:   "ratio",
    EnvVar: "RATIO",
  })
```
Any plans of adding this?

**Comment by jawher** [comment]
Hi and thanks for raising the issue.

I'll work on this as soon as I can find the time.

a PR would be more than welcome (and should not be very hard to implement) 👍 😋
