### ISSUE TITLE
Please make a release that includes the go.mod file

### ISSUE THREAD

**Issue by nim-nim** [jawher/mow.cli#88]
Adding module support is really nice but it does not help a lot if it does not end up in an actual release (since the whole point of modules is to help Go users to manage versions)

**Comment by jawher** [comment]
Done, please see the 
https://github.com/jawher/mow.cli/releases/tag/v1.0.5 release

**Comment by nim-nim** [comment]
Wonderful, I can make it the cornerstone of my "convert codebase to modules" effort . Thanks a lot!

**Comment by nim-nim** [comment]
Wonderful, I can make it the cornerstone of my "convert codebase to modules" effort . Thanks a lot!
