### ISSUE TITLE
String flags don't support the string contains space.

### ISSUE THREAD

**Issue by sunclx** [jawher/mow.cli#9]
`cli -s="Swartz Chen"`will fail.

**Comment by jawher** [comment]
I can't reproduce the problem you're describing.

Can you provide a test program which exhibits this behavior and the output you are getting ?

Thanks.

**Comment by sunclx** [comment]
```go
package main

import (
	"fmt"
	"github.com/jawher/mow.cli"
	"os"
)

func main() {
	app := cli.App("cli", "mow.cli test")
	s := app.StringOpt("s string", "", "s string")
	app.Action = func() {
		fmt.Println(*s)
	}
	app.Run(os.Args)
}
```

`cli -s="Hello" `is OK.`
`cli -s="Hello World!"` fails.

**Comment by jawher** [comment]
Weird, I tested your program and it works flawlessly for me.

When you say that it fails, do you get an error message ? Or maybe a wrong value ?

Also, what is your environment ? (OS, shell, go version).

**Comment by sunclx** [comment]
I think I know the problem.
OS: windows x32.
shell: sublime text 3.
go version: 1.4.1.
It is the problem of sublime text 3. It works wel when I change the shell.

**Comment by jawher** [comment]
Glad to see you figured it out !

**Comment by xlab** [comment]
I'm using OS X and iTerm2 (Build 3.0.4), got the same issue there :(
